openapi: 3.0.3
info:
  title: 'Axie Origin Data'
  version: '1.0'
  description: "This API about Axie Infinity: Origin will provide all the information you need about this NFT game \U0001F4AA"
  contact:
    name: Tony Duong
    url: 'https://tonystrawberry.codes'
    email: tony.duong.102@gmail.com
  license:
    name: MIT License
servers:
  - url: 'http://localhost:3000'
    description: Local
paths:
  /api/v1/cards:
    parameters: []
    get:
      summary: Get All Cards
      tags: []
      responses:
        '200':
          description: Cards found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Card'
      operationId: get-api-v1-cards
      description: 'Retrieve all the Axie Infinity: Origin cards'
      tags:
        - cards
  '/api/v1/cards/:id':
    parameters: []
    get:
      summary: Get Card by ID
      operationId: 'get-api-v1-cards-:id'
      responses:
        '200':
          description: Card found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card'
        '404':
          description: Card not found
      description: Retrieve a card by ID
      tags:
        - cards
  /api/v1/cards/search:
    post:
      summary: Search for Cards
      tags: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                string:
                  type: string
                part: 
                  type: array
                  items:
                    $ref: '#/components/schemas/EnumPart'
                class:
                  type: array
                  items:
                    $ref: '#/components/schemas/EnumClass'
                energyCost:
                  type: array
                  items:
                    $ref: '#/components/schemas/EnumEnergyCost'
                tags: 
                  type: array
                  items:
                    $ref: '#/components/schemas/EnumTag'
        tags:
        - cards
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Card'
              examples: {}
      operationId: get-api-v1-cards-search
      description: Search for specific cards
components:
  schemas:
    EnumClass:
      type: string
      enum: 
        - aquatic
        - beast
        - bird
        - bug
        - plant
        - reptile
    EnumPart:
      type: string
      enum:
        - eyes
        - ears
        - back
        - horn
        - mouth
        - tail
    EnumEffect:
      type: string
      enum:
        - attack
        - heal
        - shield
    EnumEnergyCost:
      type: number
      enum:
        - 0
        - 1
        - 2
        - 3
    EnumTag:
      type: string
      enum:
        - attack
        - skill
        - power
        - secret
        - retain
        - innate
        - banish
    Card:
      title: Card
      type: object
      description: 'Axie Infinity: Origin - Card'
      properties:
        id:
          type: integer
        class:
          $ref: '#/components/schemas/EnumClass'
        part:
          $ref: '#/components/schemas/EnumPart'
        energyCost:
          $ref: '#/components/schemas/EnumEnergyCost'
        value:
          type: integer
          example: 0
        effect:
          $ref: '#/components/schemas/EnumEffect'
        name:
          type: string
        description:
          type: string
        abilities:
          type: array
          items:
            $ref: '#/components/schemas/EnumTag'
        illustrationUrl:
          type: string
      required:
        - id
        - class
        - part
        - energyCost
        - name
        - description
        - illustrationUrl
  securitySchemes: {}
