openapi: 3.0.3
info:
  title: 'Axie Origin Data'
  version: '1.0'
  description: "This API about Axie Infinity: Origin will provide all the information you need about this NFT game \U0001F4AA"
  contact:
    name: Tony Duong
    url: 'https://tonystrawberry.codes'
    email: tony.duong.102@gmail.com
  license:
    name: MIT License
servers:
  - url: 'http://localhost:3000'
    description: Local
paths:
  /api/v1/cards:
    parameters: []
    get:
      summary: Get All Cards
      tags: 
        - cards
      responses:
        '200':
          description: Cards found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Card'
      operationId: get-api-v1-cards
      description: 'Retrieve all the Axie Infinity: Origin cards'
        
  '/api/v1/cards/:id':
    parameters: []
    get:
      summary: Get Card by ID
      tags: 
        - cards
      operationId: 'get-api-v1-cards-:id'
      responses:
        '200':
          description: Card found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card'
        '404':
          description: Card not found
      description: Retrieve a card by ID
  /api/v1/cards/search:
    post:
      summary: Search for Cards
      tags: 
        - cards
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                string:
                  type: string
                part: 
                  type: array
                  items:
                    $ref: '#/components/schemas/EnumPart'
                class:
                  type: array
                  items:
                    $ref: '#/components/schemas/EnumClass'
                energyCost:
                  type: array
                  items:
                    $ref: '#/components/schemas/EnumEnergyCost'
                tags: 
                  type: array
                  items:
                    $ref: '#/components/schemas/EnumTag'
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Card'
              examples: {}
      operationId: get-api-v1-cards-search
      description: Search for specific cards
  /api/v1/charms:
    parameters: []
    get:
      summary: Get All Charms
      tags: 
        - charms
      responses:
        '200':
          description: Charms found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Charm'
      operationId: get-api-v1-charms
      description: 'Retrieve all the Axie Infinity: Origin charms'
  /api/v1/curses:
    parameters: []
    get:
      summary: Get All Curses
      tags: 
        - curses
      responses:
        '200':
          description: Curses found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Curse'
      operationId: get-api-v1-curses
      description: 'Retrieve all the Axie Infinity: Origin curses'
  /api/v1/effects:
    parameters: []
    get:
      summary: Get All Effects
      tags: 
        - effects
      responses:
        '200':
          description: Effects found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Effect'
      operationId: get-api-v1-effects
      description: 'Retrieve all the Axie Infinity: Origin effects'
  /api/v1/runes:
    parameters: []
    get:
      summary: Get All Runes
      tags: 
        - runes
      responses:
        '200':
          description: Runes found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rune'
      operationId: get-api-v1-runes
      description: 'Retrieve all the Axie Infinity: Origin runes'
  /api/v1/tools:
    parameters: []
    get:
      summary: Get All Tools
      tags: 
        - tools
      responses:
        '200':
          description: Tool found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tool'
      operationId: get-api-v1-tools
      description: 'Retrieve all the Axie Infinity: Origin tools'
components:
  schemas:
    EnumClass:
      type: string
      enum: 
        - aquatic
        - beast
        - bird
        - bug
        - plant
        - reptile
        - neutral
        - mech
        - dusk
        - neutral
    EnumPart:
      type: string
      enum:
        - eyes
        - ears
        - back
        - horn
        - mouth
        - tail
    EnumEffect:
      type: string
      enum:
        - damage
        - heal
        - shield
    EnumEnergyCost:
      type: number
      enum:
        - 0
        - 1
        - 2
        - 3
    EnumTag:
      type: string
      enum:
        - attack
        - skill
        - power
        - secret
        - retain
        - innate
        - banish
        - unplayable
        - ethereal
    EnumCategory:
      type: string
      enum:
        - buff
        - debuff
        - neutral
    Card:
      title: Card
      type: object
      description: 'Axie Infinity: Origin - Card'
      properties:
        id:
          type: string
        class:
          $ref: '#/components/schemas/EnumClass'
        part:
          $ref: '#/components/schemas/EnumPart'
        energyCost:
          $ref: '#/components/schemas/EnumEnergyCost'
        value:
          type: integer
          example: 0
        effect:
          $ref: '#/components/schemas/EnumEffect'
        name:
          type: string
        description:
          type: string
        abilities:
          type: array
          items:
            $ref: '#/components/schemas/EnumTag'
      required:
        - id
        - class
        - part
        - energyCost
        - name
        - description
        - abilities
    Charm:
      title: Charm
      type: object
      description: 'Axie Infinity: Origin - Charm'
      properties:
        id:
          type: string
        class:
          $ref: '#/components/schemas/EnumClass'
        value:
          type: integer
          example: 0
        name:
          type: string
        description:
          type: string
      required:
        - id
        - class
        - name
        - description
    Curse:
      title: Curse
      type: object
      description: 'Axie Infinity: Origin - Curse'
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        abilities:
          type: array
          items:
            $ref: '#/components/schemas/EnumTag'
      required:
        - id
        - name
        - description
        - abilities
    Effect:
      title: Effect
      type: object
      description: 'Axie Infinity: Origin - Effect'
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        category:
          $ref: EnumCategory
      required:
        - id
        - name
        - description
        - category
    Rune:
      title: Rune
      type: object
      description: 'Axie Infinity: Origin - Rune'
      properties:
        id:
          type: string
        class:
          $ref: '#/components/schemas/EnumClass'
        name:
          type: string
        description:
          type: string
      required:
        - id
        - class
        - name
        - description
    Tool:
      title: Tool
      type: object
      description: 'Axie Infinity: Origin - Tool'
      properties:
        id:
          type: string
        energyCost:
          $ref: '#/components/schemas/EnumEnergyCost'
        value:
          type: integer
          example: 0
        effect:
          $ref: '#/components/schemas/EnumEffect'
        name:
          type: string
        description:
          type: string
        abilities:
          type: array
          items:
            $ref: '#/components/schemas/EnumTag'
      required:
        - id
        - energyCost
        - value
        - effect
        - name
        - description
        - abilities
  securitySchemes: {}
