openapi: 3.0.3
info:
  contact:
    email: tony.duong.102@gmail.com
    name: Tony Duong
    url: https://tonystrawberry.codes
  description: 'This API about Axie Infinity: Origin will provide all the information
    you need about this NFT game 💪'
  license:
    name: MIT License
  title: Axie Origin Data
  version: "1.0"
servers:
- description: Local
  url: http://localhost:3000
paths:
  /api/v1/cards:
    get:
      description: 'Retrieve all the Axie Infinity: Origin cards'
      operationId: get-api-v1-cards
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Card'
                type: array
          description: Cards found
      summary: Get All Cards
      tags: []
  /api/v1/cards/:id:
    get:
      description: Retrieve a card by ID
      operationId: get-api-v1-cards-:id
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card'
          description: Card found
        "404":
          description: Card not found
      summary: Get Card by ID
  /api/v1/cards/search:
    get:
      description: Search for specific cards
      operationId: get-api-v1-cards-search
      parameters:
      - description: Searched string (`name` and `description` fields)
        explode: true
        in: query
        name: string
        required: false
        schema:
          type: string
        style: form
      - description: Searched classes
        explode: true
        in: query
        name: class
        required: false
        schema:
          items:
            enum:
            - aquatic
            - beast
            - bird
            - bug
            - plant
            - reptile
            type: string
          type: array
        style: form
      - description: Searched part
        explode: true
        in: query
        name: part
        required: false
        schema:
          items:
            enum:
            - eyes
            - ears
            - back
            - horn
            - mouth
            - tail
            type: string
          type: array
        style: form
      - description: Search energy cost
        explode: true
        in: query
        name: energyCost
        required: false
        schema:
          items:
            enum:
            - "0"
            - "1"
            - "2"
            - "3"
            type: string
          type: array
        style: form
      - description: Searched tags
        explode: true
        in: query
        name: tags
        required: false
        schema:
          items:
            enum:
            - attack
            - skill
            - power
            - secret
            - retain
            - innate
            - banish
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              examples: {}
              schema:
                items:
                  $ref: '#/components/schemas/Card'
                type: array
          description: Search results
      summary: Search for Cards
      tags: []
components:
  schemas:
    Card:
      description: 'Axie Infinity: Origin - Card'
      example:
        abilities:
        - attack
        - attack
        part: eyes
        effect: attack
        name: name
        description: description
        id: 0
        class: aquatic
        value: 0
        energyCost: 6
      properties:
        id:
          type: integer
        class:
          enum:
          - aquatic
          - beast
          - bird
          - bug
          - plant
          - reptile
          type: string
        part:
          enum:
          - eyes
          - ears
          - back
          - horn
          - mouth
          - tail
          type: string
        energyCost:
          enum:
          - 0
          - 1
          - 2
          - 3
          type: integer
        value:
          example: 0
          type: integer
        effect:
          enum:
          - attack
          - heal
          - shield
          type: string
        name:
          type: string
        description:
          type: string
        abilities:
          items:
            enum:
            - attack
            - retain
            - banish
            - skill
            - secret
            - power
            type: string
          type: array
      required:
      - class
      - energyCost
      - id
      - name
      - part
      title: Card
      type: object
  securitySchemes: {}
