openapi: 3.1.0
info:
  title: Axie Origin Data
  version: '1.0'
  summary: 'API for returning Axie Infinity: Origin Data such as Cards, Runes, Charms...'
  description: "This API about Axie Infinity: Origin will provide all the information you need about this NFT game \U0001F4AA"
  contact:
    name: Tony Duong
    url: 'https://tonystrawberry.codes'
    email: tony.duong.102@gmail.com
  license:
    name: MIT License
servers:
  - url: 'http://localhost:3000'
    description: Local
paths:
  /api/v1/cards:
    parameters: []
    get:
      summary: Get All Cards
      tags: []
      responses:
        '200':
          description: Cards found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Card'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
      operationId: get-api-v1-cards
      description: 'Retrieve all the Axie Infinity: Origin cards'
  '/api/v1/cards/:id':
    parameters: []
    get:
      summary: Get Card by ID
      operationId: 'get-api-v1-cards-:id'
      responses:
        '200':
          description: Card found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card'
        '404':
          description: Card not found
      description: Retrieve a card by ID
  /api/v1/cards/search:
    get:
      summary: Search for Cards
      tags: []
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Card'
              examples: {}
      operationId: get-api-v1-cards-search
      parameters:
        - schema:
            type: string
          in: query
          name: string
          description: Searched string (`name` and `description` fields)
        - schema:
            type: array
            enum:
              - aquatic
              - beast
              - bird
              - bug
              - plant
              - reptile
          in: query
          name: class
          description: Searched classes
        - schema:
            type: array
            enum:
              - eyes
              - ears
              - back
              - horn
              - mouth
              - tail
          in: query
          name: part
          description: Searched part
        - schema:
            type: array
            enum:
              - 0
              - 1
              - 2
              - 3
          in: query
          name: energyCost
          description: Search energy cost
        - schema:
            type: array
            enum:
              - attack
              - skill
              - power
              - secret
              - retain
              - innate
              - banish
          in: query
          name: tags
          description: Searched tags
      description: Search for specific cards
components:
  schemas:
    Card:
      title: Card
      type: object
      description: 'Axie Infinity: Origin - Card'
      examples:
        - id: 1
          class: aquatic
          part: wing
          energyCost: '1'
          value: 50
          effect: attack
          name: Anemone
          description: 'Whenever this is drawn, heal 20 HP.'
          abilities:
            - attack
      properties:
        id:
          type: integer
        class:
          type: string
          enum:
            - aquatic
            - beast
            - bird
            - bug
            - plant
            - reptile
        part:
          type: string
          enum:
            - eyes
            - ears
            - back
            - horn
            - mouth
            - tail
        energyCost:
          type: integer
          enum:
            - 0
            - 1
            - 2
            - 3
        value:
          type: integer
          example: 0
        effect:
          type: string
          enum:
            - attack
            - heal
            - shield
        name:
          type: string
        description:
          type: string
        abilities:
          type: array
          items:
            type: string
            enum:
              - attack
              - retain
              - banish
              - skill
              - secret
              - power
      required:
        - id
        - class
        - part
        - energyCost
        - name
  securitySchemes: {}
